// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/coinsv1/coins.proto

package coinsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // required (coin/account id)
	Initial       int64                  `protobuf:"varint,2,opt,name=initial,proto3" json:"initial,omitempty"` // optional, default 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_coinsv1_coins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coinsv1_coins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_coinsv1_coins_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRequest) GetInitial() int64 {
	if x != nil {
		return x.Initial
	}
	return 0
}

type DepleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // required (coin/account id)
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`              // required, must be > 0
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // required (UUID) - actor responsible for depletion
	DataId        string                 `protobuf:"bytes,4,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // optional event id (e.g., "order:12345")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepleteRequest) Reset() {
	*x = DepleteRequest{}
	mi := &file_api_coinsv1_coins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepleteRequest) ProtoMessage() {}

func (x *DepleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coinsv1_coins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepleteRequest.ProtoReflect.Descriptor instead.
func (*DepleteRequest) Descriptor() ([]byte, []int) {
	return file_api_coinsv1_coins_proto_rawDescGZIP(), []int{1}
}

func (x *DepleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepleteRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepleteRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type AccountReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coins            int64                  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	LastRechargeDate string                 `protobuf:"bytes,3,opt,name=last_recharge_date,json=lastRechargeDate,proto3" json:"last_recharge_date,omitempty"` // RFC3339
	LastUsageDate    string                 `protobuf:"bytes,4,opt,name=last_usage_date,json=lastUsageDate,proto3" json:"last_usage_date,omitempty"`          // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountReply) Reset() {
	*x = AccountReply{}
	mi := &file_api_coinsv1_coins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReply) ProtoMessage() {}

func (x *AccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_coinsv1_coins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReply.ProtoReflect.Descriptor instead.
func (*AccountReply) Descriptor() ([]byte, []int) {
	return file_api_coinsv1_coins_proto_rawDescGZIP(), []int{2}
}

func (x *AccountReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountReply) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *AccountReply) GetLastRechargeDate() string {
	if x != nil {
		return x.LastRechargeDate
	}
	return ""
}

func (x *AccountReply) GetLastUsageDate() string {
	if x != nil {
		return x.LastUsageDate
	}
	return ""
}

var File_api_coinsv1_coins_proto protoreflect.FileDescriptor

const file_api_coinsv1_coins_proto_rawDesc = "" +
	"\n" +
	"\x17api/coinsv1/coins.proto\x12\bcoins.v1\"9\n" +
	"\rCreateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\ainitial\x18\x02 \x01(\x03R\ainitial\"j\n" +
	"\x0eDepleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x04 \x01(\tR\x06dataId\"\x8a\x01\n" +
	"\fAccountReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05coins\x18\x02 \x01(\x03R\x05coins\x12,\n" +
	"\x12last_recharge_date\x18\x03 \x01(\tR\x10lastRechargeDate\x12&\n" +
	"\x0flast_usage_date\x18\x04 \x01(\tR\rlastUsageDate2\x8d\x01\n" +
	"\fCoinsService\x12@\n" +
	"\rCreateAccount\x12\x17.coins.v1.CreateRequest\x1a\x16.coins.v1.AccountReply\x12;\n" +
	"\aDeplete\x12\x18.coins.v1.DepleteRequest\x1a\x16.coins.v1.AccountReplyB=Z;github.com/devifyX/go-back-coin-service/api/coinsv1;coinsv1b\x06proto3"

var (
	file_api_coinsv1_coins_proto_rawDescOnce sync.Once
	file_api_coinsv1_coins_proto_rawDescData []byte
)

func file_api_coinsv1_coins_proto_rawDescGZIP() []byte {
	file_api_coinsv1_coins_proto_rawDescOnce.Do(func() {
		file_api_coinsv1_coins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_coinsv1_coins_proto_rawDesc), len(file_api_coinsv1_coins_proto_rawDesc)))
	})
	return file_api_coinsv1_coins_proto_rawDescData
}

var file_api_coinsv1_coins_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_coinsv1_coins_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: coins.v1.CreateRequest
	(*DepleteRequest)(nil), // 1: coins.v1.DepleteRequest
	(*AccountReply)(nil),   // 2: coins.v1.AccountReply
}
var file_api_coinsv1_coins_proto_depIdxs = []int32{
	0, // 0: coins.v1.CoinsService.CreateAccount:input_type -> coins.v1.CreateRequest
	1, // 1: coins.v1.CoinsService.Deplete:input_type -> coins.v1.DepleteRequest
	2, // 2: coins.v1.CoinsService.CreateAccount:output_type -> coins.v1.AccountReply
	2, // 3: coins.v1.CoinsService.Deplete:output_type -> coins.v1.AccountReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_coinsv1_coins_proto_init() }
func file_api_coinsv1_coins_proto_init() {
	if File_api_coinsv1_coins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_coinsv1_coins_proto_rawDesc), len(file_api_coinsv1_coins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coinsv1_coins_proto_goTypes,
		DependencyIndexes: file_api_coinsv1_coins_proto_depIdxs,
		MessageInfos:      file_api_coinsv1_coins_proto_msgTypes,
	}.Build()
	File_api_coinsv1_coins_proto = out.File
	file_api_coinsv1_coins_proto_goTypes = nil
	file_api_coinsv1_coins_proto_depIdxs = nil
}
